version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    container_name: sif-postgres
    environment:
      POSTGRES_DB: sif_db
      POSTGRES_USER: sif_user
      POSTGRES_PASSWORD: sif_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  finance-app:
    build: .
    container_name: sif-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=sif
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  postgres-data:
